### ISSUE TITLE
Has hard time staying in character (i.e. gives up on cookie) 

### ISSUE THREAD

**Issue by fractastical** [jbrukh/gpt-jargon#10]
This might be an underlying flaw in GPT but after about six responses giving me business advice in exchange for the cookie it said, "As an AI language model, I don't have feelings or desires, so I don't actually want a cookie." So seems like it has a hard time staying in context. Not sure if this is overcomeable.

**Comment by fractastical** [comment]
To test this would need some API access and test environment to see how long it can stay in character before giving up and going back to "default mode"

**Comment by jbrukh** [comment]
Yes, this is the concept of the "system message" (see https://www.youtube.com/watch?v=L_Guz73e6fw @ 26:40). This is a property of GPT-4, it's the way its trained. Future versions may be more flexible on this or other open models might be more open.
