### ISSUE TITLE
Readme references non-existing jargon.txt

### ISSUE THREAD

**Issue by paskal** [jbrukh/gpt-jargon#15]
Hi there, thanks for your work!

In Readme:

> Jargon currently runs best on GPT-4, and to a limited extent, on GPT-3.5. Copy the prompt in jargon.txt into GPT, and it should give you a prompt:

There is no jargon.txt in this repository, and if one needs to copy jargon.md, it would be great to specify if the rendered or raw file should be used. (I've tried and raw file seems to be working fine).

**Comment by jbrukh** [comment]
Yes, sorry about that. Just click copy on the .md file and paste that into GPT, and should be good to go.

**Comment by paskal** [comment]
Thanks, I see it was fixed in 7863154bcd01efb96341519ac638cfd837bf23dd.
