### ISSUE TITLE
jargon: error handling

### ISSUE THREAD

**Issue by rabsef-bicrym** [jbrukh/gpt-jargon#3]
Suggest classes of errors that GPT commonly falls into, such that it can output `%ethics-error` e.g. rather than long text.

**Comment by jbrukh** [comment]
Good idea!

**Comment by jbrukh** [comment]
What are some examples of errors you have seen?

**Comment by rabsef-bicrym** [comment]
I've seen the classical ethics boundary issue: "As an AI language model, I can't be mean". I'm sure there are others which could probably be sorted into classes, just to keep the program in loop: If you need to inform the user that GPT cannot complete a command due to an ethical boundary, print %jargon-error-ethics then print the command prompt. Do not explain the error further to the user. or so.

**Comment by rabsef-bicrym** [comment]
<img width="777" alt="image" src="https://user-images.githubusercontent.com/52549148/227738088-e4a1a2ec-de24-43fb-a5e8-279508d892e1.png">

**Comment by jbrukh** [comment]
Oooh. Very good example. Any idea how to implement?

**Comment by jbrukh** [comment]
Trying this:

    * (Errors) If the LLM doesn't want to give an output due to ethical or safety issues, the interpreter will produce an ERROR. ERRORs start with % and give more detail in /verbose or /debug mode.

**Comment by jbrukh** [comment]
Seems to work!
