### ISSUE TITLE
jargon: formalize `/execute procedure(parameter1,...,parametern)`

### ISSUE THREAD

**Issue by rabsef-bicrym** [jbrukh/gpt-jargon#5]
I'm not identifying how parameters are intended to be called against procedures. I think this could be formally specified making better, more specific, calls to execute.

**Comment by rabsef-bicrym** [comment]
It might be good to use something other than a comma, that is more obscure. A pipe character, for instance. This could help it differentiate from commas in the PARAMETERs and PARAMETER delimiters.

**Comment by jbrukh** [comment]
As of `v0.0.10`, basic params that are specified look like:

    # sum two numbers
    +++ func($x, $y)
    - Return sum
    +++

Most readable way to pass might be to define the variables first. Remember you can also use axioms to modify how parameters are passed inline.

**Comment by jbrukh** [comment]
You can also specify what you want the return values to look like. This doesn't need to be spec'd, it can just be divined by the interpreter.

        # sum two numbers
        +++ func($x, $y) returns only numbers
        - Return sum
        +++

        > [error!]

But maybe more idiomatic way would be via axioms:

        # sum two numbers
        +++ func($x, $y)
        * Returns only numbers
        - Return sum
        +++

**Comment by jbrukh** [comment]
You can still pass parameters as variables:

    $msg = "Dear Santa,
    I want a train for Christmas."
    
    +++ display($msg, $num)
    - Display $msg $num times
    +++

    /display($msg, 10)
