### ISSUE TITLE
jargon: can we make it have functions and subroutines?

### ISSUE THREAD

**Issue by rabsef-bicrym** [jbrukh/gpt-jargon#6]
Define:
`subroutine` an internal operation that is not allowed to cause printed output
`function` an internal operation that may call subroutines and print output

If a subroutine is called, it should have the ability to return new `ATOM`s `AXIOMs` or `INSTRUCTIONs` to the `SCOPE` of the operation calling it into existence.

**Comment by rabsef-bicrym** [comment]
Here is a rationale for incorporating this convention. Imagine the following jargon:
```jargon

+++ parseEmail($emailContents)
  - $emailContents will contain an email thread, formatted as follows
    ```
    Subject: {emailSubject}
    ***
    Body:
    {
        newEmail
        ****
        emailThread
    }
    ```
  - Separate these into three output values:
    ```
    $emailSubject
    $newEmail
    $emailThread
    ```
  - Return these three values to the SCOPE of the PROCEDURE calling the parseEmail PROCEDURE.
+++

+++ professionalismFeedback($new,$past)
  - $new is a limited draft of an email that is responsive to $past.
  - $past is a thread of emails that led to the drafting of $new.
  - There may be more than one email in $past. For your purposes, focus on the most recent (top) email in $past.
  - Check $new for responsiveness to $past.
  - Check $new for a professional and courteous tone. It should be warm and welcoming while also concisely delivering information.
  - Check $new for word choice and grammar.
  - Check $new for overall framing issues (order of responses, e.g.)
  - Return a text to the SCOPE of the PROCEDURE calling the professionalismFeedback PROCEDURE as in the following example:
    ```
    - [responsiveness] - Your draft did not respond to <point A> brought up in the last email <citation from $past>
    - [tone] - The phrase "check you later" is not professional, and could be replaced with "I hope to speak with you soon."
    - [word-choice/grammar] - For subject agreement, change "the dogs is outside" to "the dogs _are_ outside"
    - [framing] - Split your first paragraph into two sub-paragraphs, as it discusses two separate topics: <a> and <b> topics.
+++

+++ redraftEmail($new,$past,$feedback)
  - $new is a limited draft of an email that is responsive to $past.
  - $past is a thread of emails that led to the drafting of $new.
  - There may be more than one email in $past. For your purposes, focus on the most recent (top) email in $past.
  - Review $feedback, then draft a version of $new that incorporates the suggestions made in $feedback.
+++

+++ rsvpIFY($rawEmail)
  - The next INSTRUCTION will ask you to call a subroutine which will return three output values:
    ```
    $emailSubject
    $newEmail
    $emailThread
    ```
  - /execute parseEmail($rawEmail)
  - The $emailSubject value is the subject line of an email.
  - The $emailThread is an email thread to which the $newEmail is intended to be responsive
  - The $newEmail value is an unordered list of responses to the $emailThread.
  * The $emailThread cannot be changed - it is a historical record of a conversation.
  * If the $emailSubject begins with `FWD:` or `RE:` it cannot be changed - it is a historical record of the prior subject.

  - The next INSTRUCTION will ask you to call a function which will return a string-type value:
    ```
    $professionalismFeedback
    ```
  - /execute professionalismFeedback($newEmail,$emailThread)

  - The next INSTRUCTION will ask you to call a function which will return a string-type value:
    ```
    $redraftEmail
    ```
  - /execute redraftEmail($newEmail,$emailThread,$professionalismFeedback)
  - Print your output as in the example below, in human legible text, not in a code-block, replacing the PARAMETERs listed with their current value:
    ```
    Suggestions:
      $professionalismFeedback
    
    ----
    Subject: $emailSubject

    Draft:
      $redraftEmail
    ----
    ```
+++
```

Here we have some functions and some subroutines. We need a way of declaring faces on values when subroutines return. I was overly protective with these in my code to try and make it do what I wanted but this proves that it can. Consider this input:

```
/execute rsvpIFY(
Subject: {RE: Requesting a few answers for your welcome email}
***
Body:
{
    Martin,
    - My name is Eric <redacted>
    - My shoe size is 9.5 (please convert this to display as a fraction)
    - I don't know the capital of Uganda

    ***
    Eric,
    Could you please provide me with some details for your welcome email? We're about to send it out. I just need to know:
    1. What is your shoe size?
    2. What is your name?
    3. What is the capital of Uganda
    4. Why is a raven like a writing desk?

    Regards,

    Your manager, Martin Shop
})
```

Note that here we suffer from the issue I described in #5 where it's hard to specify where your arguments begin and end.

Our output, nonetheless, was really good (Better than 3.5 with the system prompts I was using:
```
Suggestions:

[responsiveness] - Your draft did not respond to the question "Why is a raven like a writing desk?" from the last email.
[tone] - The phrase "I don't know the capital of Uganda" could be replaced with "I am unsure of the capital of Uganda."
[word-choice/grammar] - No issues found.
[framing] - No issues found.
Subject: RE: Requesting a few answers for your welcome email

Draft:
Martin,

My name is Eric <redacted>
My shoe size is 19/2
I am unsure of the capital of Uganda
Regards,
Eric
```

My redraft function still needs work - I want it to flexibly handle unordered email response lists and partially drafted emails and turn both into prose. Will work on it.

**Comment by jbrukh** [comment]
Please note that parameters are specified as of 0.0.9, and a procedure can call another procedure.

    +++ fib($n)
    -- Return the $n-th Fibonacci number
    +++

    +++ print-fib
    -- Print fib($n) for $n from 1 to 10
    * Output to a single line
    +++

Jargon also divines other subroutine type behavior like inline functions:

    +++ print-fib
    * fib($n) <- $n-th Fibonacci number
    -- Print fib($n) for $n from 1 to 10
    +++
